name: Publish

on:
  push:
    tags: [ "v*" ]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: prep
      run: |
        DOCKER_IMAGE=ghcr.io/justfaas/operator
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:latest"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "tags=${TAGS}" >> $GITHUB_OUTPUT
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ steps.prep.outputs.tags }}
        platforms: linux/amd64,linux/arm64
        secrets: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        tag_name: ${{ github.ref_name }}
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}
